### ISSUE TITLE
neukazuje pritomnost v DB pri epizodach serialov

### ISSUE THREAD

**Issue by filipr11** [Marek71cz/sc2-integrate#1]
![image](https://user-images.githubusercontent.com/62966223/84682973-c1a2fb00-af36-11ea-8369-9d7119be26ba.png)
![image](https://user-images.githubusercontent.com/62966223/84683007-d1224400-af36-11ea-8009-8ba0b5a8e74d.png)
![image](https://user-images.githubusercontent.com/62966223/84683037-dbdcd900-af36-11ea-9f15-3a2ac8781c52.png)
 
Na stranke serie serialu funguje script ale u niektorych serialov chybaju jednotlive diely a vtedy sa neda zistit ci su v DB

**Comment by Marek71cz** [comment]
Ano, u epizod to nefunguje. Plánuji to dodělat až budu mít k dispozici API.

**Comment by Marek71cz** [comment]
Doděláno pro ČSFD a IMDB - u epizod se objevuje logo SC2, pokud je epizoda v DB. A taky se objeví info text o streamech.
